version: 2
jobs:
  build:
    machine:
      image: windows-default
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            cd app && npm install
      - run:
          name: Build
          command: |
            npm run build
      - store_artifacts:
          path: test-reports/
          destination: tr1